@Todo_HostAddress = https://localhost:7104

POST {{Todo_HostAddress}}/tasks
Content-Type: application/json

{
    "taskDescription": "Grocery Shopping",
    "dueDate": "2024-04-30T11:00:00.000000Z",
    "completed": false
}

###

POST {{Todo_HostAddress}}/tasks
Content-Type: application/json

{
    "taskDescription": "Clean House",
    "dueDate": "2024-05-10T15:00:00.000000Z",
    "completed": false
}

###

POST {{Todo_HostAddress}}/tasks
Content-Type: application/json

{
    "taskDescription": "Blog Post",
    "dueDate": "2024-05-20T00:00:00.000000Z",
    "completed": false
}

###

POST {{Todo_HostAddress}}/tasks
Content-Type: application/json

{
    "taskDescription": "   Bl   ",
    "dueDate": "2024-05-20T00:00:00.000000Z",
    "completed": false
}
